apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml

configMapGenerator:
  - name: iota-detection-rules
    files:
      - ../../rules/aws_cloudtrail/

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: iota
