{{- if and .Values.persistence.events.enabled (not .Values.persistence.events.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iota.fullname" . }}-events
  labels:
    {{- include "iota.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.events.accessMode }}
  {{- if .Values.persistence.events.storageClass }}
  storageClassName: {{ .Values.persistence.events.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.events.size }}
{{- end }}
---
{{- if .Values.persistence.state.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iota.fullname" . }}-state
  labels:
    {{- include "iota.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.state.accessMode }}
  {{- if .Values.persistence.state.storageClass }}
  storageClassName: {{ .Values.persistence.state.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.state.size }}
{{- end }}
